export const unitTypes = [
    "YARN_SPINNING",
    "YARN_PROCESSING",
    "WEAVING_UNIT",
    "KNITTING_UNIT",
    "DYEING_UNIT",
    "FABRIC_PROCESSING_UNIT",
    "FABRIC_FINISHING_UNIT",
    "WASHING_UNIT",
    "CUTTING_UNIT",
    "COMPUTERIZED_EMBROIDERY_UNIT",
    "MANUAL_EMBROIDERY_UNIT",
    "FUSING_UNIT",
    "PRINTING_UNIT",
    "STITCHING_UNIT",
    "CHECKING_UNIT",
    "IRONING_PACKING_UNIT",
    "KAJA_BUTTON_UNIT",
    "MULTI_NEEDLE_DOUBLE_CHAIN_UNIT",
    "OIL_REMOVING_MENDING_CENTER",
    "PATTERN_MAKING_CENTER",
    "FILM_SCREEN_MAKING_CENTER",
];
export const availableCertifications = [
    "Import Export Certificate",
    "ISO 9001",
    "GOTS",
    "Fair Trade",
    "OEKO-TEX",
    "SA8000",
    "RCS",
    "BCI Cotton",
    "Sedex",
    "OCS",
    "GRS",
];
export const workTypes = ["DOMESTIC_WORK", "EXPORT_WORK"];